import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Navigation from "@/components/Navigation/Navigation";
import { cookies } from "next/headers"
import { verifyToken } from "@/lib/auth"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export async function getCurrentUser() {
  const token = (await cookies()).get("auth-token")?.value

  if (!token) return null

  return verifyToken(token)
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className="content-body">
        <Header></Header>
        <Navigation></Navigation>
        <main className="page-content">
          {children}
        </main>
      </body>
    </html>
  );
}
