import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Navigation from "@/components/Navigation/Navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="content-body">
        <Header></Header>
        <Navigation></Navigation>
        <main className="page-content">
          {children}
        </main>
      </body>
    </html>
  );
}
